name: Terraform DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - '**.tf'
    #   - '**.tfvars'
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Run tfsec (Security scan)
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Optional: CD
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
